[package]
name = "recommendations"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[dependencies]
axum = "0.7.5"
serde = "1.0.199"
serde_derive = "1.0.199"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
tracing-subscriber = "0.3.18"
