#!/usr/bin/bash

set -e
set -o pipefail

backend_pid=
client_pid=
environment=${1:-dev}

function cleanup() {
  [ ! -z "$backend_pid" ] && kill -INT $backend_pid || true
  [ ! -z "$client_pid" ] && kill -INT $client_pid || true
  pkill -f "backend" || true
  pkill -f "npm run $environment" || true
}

function on_sigint() {
  echo ""
  echo "stopping processes ..."
  cleanup
  echo ""
}

trap 'on_sigint' SIGINT

cleanup
echo "starting up ..."
make -C backend $environment &
backend_pid=$!

make -C client $environment &
client=$!

wait $backend_pid
wait $client_pid
